name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: latest
    - run: emcc -v
    - run: npm ci
    - run: npm run package
      env:
        CI: true
    - run: npm test
      env:
        CI: true
